import Head from 'next/head'
import Image from 'next/image'
import { Poppins } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { HomeHeader } from '@/components/HomeHeader'
import { StackItems } from '@/components/StackItems'
import { OtherTechnologies } from '@/components/OtherTechnologies'

const poppins = Poppins({ weight: ['300', '400', '500', '600'], subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Andreas Søgaard Pedersen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${poppins.className}`}>
        <Image
          src="/AndreasSoegaardRound.png"
          alt="Andreas Søgaard Pedersen"
          className={styles.andreasImage}
          width={120}
          height={120}
          priority
        />
        <header>
          <HomeHeader />
        </header>
        <section>
          <StackItems />
          <OtherTechnologies />
        </section>
      </main>
    </>
  )
}
